# Generated by Django 5.0 on 2023-12-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='provider_id',
        ),
    ]
