version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - handoff_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    command: npm start
    volumes:
      - ./frontend:/frontend 
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - handoff_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: matt
      POSTGRES_PASSWORD: mpl
      POSTGRES_DB: handofftest
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C --data-checksums"
    ports:
      - "5433:5432"
    networks:
      - handoff_network

networks:
  handoff_network:
    external: true

volumes:
  postgres_data:
    external: true