# Generated by Django 5.0 on 2023-12-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
        ('user_app', '0002_client_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='assignment',
        ),
        migrations.AddField(
            model_name='client',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='patient_app.patient'),
        ),
    ]
