# Generated by Django 5.0 on 2023-12-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profession',
            field=models.CharField(choices=[('registered nurse', 'REGISTERED NURSE'), ('physician', 'physician')], default='registered nurse', max_length=16),
        ),
    ]
